-- DELETE FROM spring_batch.public.batch_job_execution_context WHERE job_execution_id is not null;
-- DELETE FROM spring_batch.public.batch_step_execution_context WHERE batch_step_execution_context.step_execution_id is not null;
-- DELETE FROM spring_batch.public.batch_step_execution WHERE batch_step_execution.step_execution_id is not null;
-- DELETE FROM spring_batch.public.batch_job_execution_params WHERE job_execution_id is not null;
-- DELETE FROM spring_batch.public.batch_job_execution WHERE batch_job_execution.job_execution_id is not null;
-- DELETE FROM spring_batch.public.batch_job_instance WHERE job_instance_id is not null;
